'use strict';

export enum RoleType {
  USER = 'ROLE_USER',
  ADMIN = 'ROLE_ADMIN',
  INTERNAL_STUDENT = 'ROLE_INTERNAL_STUDENT',
  EXTERNAL_STUDENT = 'ROLE_EXTERNAL_STUDENT',
  INSTRUCTOR = 'ROLE_INSTRUCTOR',
  PUBLIC = 'ROLE_PUBLIC',
  ANONYMOUS = 'ROLE_ANONYMOUS',
}
