import { getRepository, MigrationInterface, QueryRunner } from 'typeorm';
import { Book } from '../domain/book.entity';
import { BookGenre } from '../domain/enumeration/book-genre';
import { Language } from '../domain/enumeration/language';
import { BookAvailability } from '../domain/enumeration/book-availability';
import { Learner } from '../domain/learner.entity';
import { LearnerType } from '../domain/enumeration/learner-type';
import { BookBorrowRequestStatus } from '../domain/enumeration/book-borrow-request-status';
import { BookBorrowRequest } from '../domain/book-borrow-request.entity';
import { Category } from '../domain/category.entity';
import { PaymentMethod } from '../domain/payment-method.entity';
import { PaymentType } from '../domain/enumeration/payment-type';
import { Course } from '../domain/course.entity';
import { Order } from '../domain/order.entity';
import { OrderStatus } from '../domain/enumeration/order-status';

export class SeedData1570200490073 implements MigrationInterface {
  books: Book[] = [
    {
      id: 1,
      title: 'تفسير ابن كثير',
      author: 'ابن كثير',
      isbn: '9789773514554',
      genre: BookGenre.RELIGIOUS,
      publisher: 'دار ابن الجوزي',
      pageCount: 2560,
      description: 'تفسير للقرآن الكريم يعتمد على الأحاديث الصحيحة وأقوال الصحابة والتابعين.',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/ibn-kathir.jpg',
      bookUrl: 'https://example.com/ibn-kathir.pdf',
      publicationDate: new Date('2010-01-01'),
      price: 50,
      studentsPrice: 30,
      numberOfBooksAvailable: 10,
      keywords: 'تفسير, قرآن, ابن كثير',
      bookAvailability: BookAvailability.AVAILABLE_BOTH,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      coverImageFile: null,
      coverImageFileContentType: null,
      bookFile: null,
      bookFileContentType: 'application/pdf',
      categories: [],
      comments: [],
      overallRating: 4.5,
    },
    {
      id: 2,
      title: 'صحيح البخاري',
      author: 'الإمام البخاري',
      isbn: '9789773424648',
      genre: BookGenre.RELIGIOUS,
      publisher: 'دار السلام',
      pageCount: 4000,
      description: 'أصح كتاب بعد القرآن الكريم يحتوي على الأحاديث النبوية الشريفة.',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/bukhari.jpg',
      bookUrl: 'https://example.com/bukhari.pdf',
      publicationDate: new Date('1998-01-01'),
      price: 60,
      studentsPrice: 40,
      numberOfBooksAvailable: 15,
      keywords: 'حديث, صحيح البخاري, السنة',
      bookAvailability: BookAvailability.AVAILABLE_BOTH,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      coverImageFile: null,
      coverImageFileContentType: null,
      bookFile: null,
      bookFileContentType: 'application/pdf',
      categories: [],
      comments: [],
      overallRating: 4.5,
    },
    {
      id: 3,
      title: 'رياض الصالحين',
      author: 'الإمام النووي',
      isbn: '9789773424534',
      genre: BookGenre.RELIGIOUS,
      publisher: 'دار ابن حزم',
      pageCount: 800,
      description: 'مجموعة من الأحاديث النبوية المختارة التي تحث على الفضائل والأخلاق الحميدة.',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/riyad.jpg',
      bookUrl: 'https://example.com/riyad.pdf',
      publicationDate: new Date('2005-01-01'),
      price: 25,
      studentsPrice: 15,
      numberOfBooksAvailable: 20,
      keywords: 'أخلاق, حديث, رياض الصالحين',
      bookAvailability: BookAvailability.AVAILABLE_ONLINE_ONLY,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      coverImageFile: null,
      coverImageFileContentType: null,
      bookFile: null,
      bookFileContentType: 'application/pdf',
      categories: [],
      comments: [],
      overallRating: 4.5,
    },
    {
      id: 4,
      title: 'أحكام القرآن',
      author: 'الجصاص',
      isbn: '9789773424428',
      genre: BookGenre.RELIGIOUS,
      publisher: 'دار الكتب العلمية',
      pageCount: 1200,
      description: 'تفسير للأحكام الشرعية المستنبطة من آيات القرآن الكريم.',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/ahkam.jpg',
      bookUrl: 'https://example.com/ahkam.pdf',
      publicationDate: new Date('2012-01-01'),
      price: 35,
      studentsPrice: 20,
      numberOfBooksAvailable: 7,
      keywords: 'فقه, أحكام, تفسير',
      bookAvailability: BookAvailability.UNAVAILABLE,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      coverImageFile: null,
      coverImageFileContentType: null,
      bookFile: null,
      bookFileContentType: 'application/pdf',
      categories: [],
      comments: [],
      overallRating: 4.5,
    },
    {
      id: 5,
      title: 'الكشاف',
      author: 'الزمخشري',
      isbn: '9789773424433',
      genre: BookGenre.RELIGIOUS,
      publisher: 'دار الكتب العلمية',
      pageCount: 1500,
      description: 'تفسير بلاغي ولغوي للقرآن الكريم يحتوي على العديد من الفوائد اللغوية والنحوية.',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/kashaf.jpg',
      bookUrl: 'https://example.com/kashaf.pdf',
      publicationDate: new Date('2008-01-01'),
      price: 40,
      studentsPrice: 25,
      numberOfBooksAvailable: 5,
      keywords: 'بلاغة, تفسير, لغة',
      bookAvailability: BookAvailability.RESERVED,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      coverImageFile: null,
      coverImageFileContentType: null,
      bookFile: null,
      bookFileContentType: 'application/pdf',
      categories: [],
      comments: [],
      overallRating: 4.5,
    },
  ];

  learners: Learner[] = [
    {
      id: 1,
      firstName: 'محمد',
      lastName: 'علي',
      birthYear: 1990,
      email: 'mohammed.ali@example.com',
      mobileNo: '1234567890',
      googleId: 'google-id-1',
      facebookId: 'facebook-id-1',
      appleId: 'apple-id-1',
      isBanned: false,
      verifiedByEmail: true,
      verifiedByMobileNo: false,
      imageFile: null,
      imageFileContentType: '',
      imageFileUrl: 'https://example.com/mohammed-ali.jpg',
      nationalityCode: 'EG',
      city: 'القاهرة',
      address: '123 شارع رئيسي',
      learnerType: LearnerType.INTERNAL_STUDENT,
      studentId: 'student-id-1',
      notes: 'طالب ممتاز',
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      user: null,
    },
    {
      id: 2,
      firstName: 'سعيد',
      lastName: 'محمود',
      birthYear: 1985,
      email: 'saeed.mahmoud@example.com',
      mobileNo: '0987654321',
      googleId: 'google-id-2',
      facebookId: 'facebook-id-2',
      appleId: 'apple-id-2',
      isBanned: false,
      verifiedByEmail: true,
      verifiedByMobileNo: true,
      imageFile: null,
      imageFileContentType: '',
      imageFileUrl: 'https://example.com/saeed-mahmoud.jpg',
      nationalityCode: 'SA',
      city: 'الرياض',
      address: '456 شارع رئيسي',
      learnerType: LearnerType.INTERNAL_STUDENT,
      studentId: 'student-id-2',
      notes: 'مجتهد ومثابر',
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      user: null,
    },
  ];

  bookBorrowRequests: BookBorrowRequest[] = [
    {
      id: 1,
      requestDate: new Date('2024-01-10'),
      collectDate: new Date('2024-01-15'),
      returnDate: new Date('2024-02-10'),
      bookBorrowRequestStatus: BookBorrowRequestStatus.PENDING,
      book: { id: 1 } as Book, // Reference to the book with id 1
      learner: { id: 1 } as Learner, // Reference to the learner with id 1
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 2,
      requestDate: new Date('2024-02-01'),
      collectDate: new Date('2024-02-05'),
      returnDate: new Date('2024-03-01'),
      bookBorrowRequestStatus: BookBorrowRequestStatus.APPROVED,
      book: { id: 2 } as Book, // Reference to the book with id 2
      learner: { id: 2 } as Learner, // Reference to the learner with id 2
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
  ];

  categories: Category[] = [
    {
      id: 1,
      nameAr: 'القرآن الكريم',
      nameEn: 'Holy Quran',
      menuOrder: 1,
      imageFileUrl: 'https://example.com/quran.jpg',
      imageFile: null,
      imageFileContentType: '',
      notes: 'Category for Quran related books and courses',
      isActive: true,
      books: [],
      courses: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 2,
      nameAr: 'الحديث الشريف',
      nameEn: 'Hadith',
      menuOrder: 2,
      imageFileUrl: 'https://example.com/hadith.jpg',
      imageFile: null,
      imageFileContentType: '',
      notes: 'Category for Hadith related books and courses',
      isActive: true,
      books: [],
      courses: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 3,
      nameAr: 'الفقه',
      nameEn: 'Fiqh',
      menuOrder: 3,
      imageFileUrl: 'https://example.com/fiqh.jpg',
      imageFile: null,
      imageFileContentType: '',
      notes: 'Category for Fiqh related books and courses',
      isActive: true,
      books: [],
      courses: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 4,
      nameAr: 'العقيدة',
      nameEn: 'Aqidah',
      menuOrder: 4,
      imageFileUrl: 'https://example.com/aqidah.jpg',
      imageFile: null,
      imageFileContentType: '',
      notes: 'Category for Aqidah related books and courses',
      isActive: true,
      books: [],
      courses: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 5,
      nameAr: 'السيرة النبوية',
      nameEn: 'Seerah',
      menuOrder: 5,
      imageFileUrl: 'https://example.com/seerah.jpg',
      imageFile: null,
      imageFileContentType: '',
      notes: 'Category for Seerah related books and courses',
      isActive: true,
      books: [],
      courses: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
  ];

  paymentMethods: PaymentMethod[] = [
    {
      id: 1,
      nameAr: 'البطاقة المصرقية',
      nameEn: 'Local Credit Cards',
      menuOrder: 1,
      imageFileUrl: 'https://example.com/cash-on-delivery.jpg',
      imageFile: null,
      imageFileContentType: '',
      details: 'الدفع نقدا عند استلام الطلب',
      feePercentage: 0,
      paymentType: PaymentType.MOAMALAT,
      isActive: true,
      notes: 'خدمة الدفع عند الاستلام',
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 2,
      nameAr: 'ادفعلي',
      nameEn: 'Adfali',
      menuOrder: 2,
      imageFileUrl: 'https://example.com/credit-card.jpg',
      imageFile: null,
      imageFileContentType: '',
      details: 'الدفع بواسطة بطاقة ائتمانية',
      feePercentage: 2,
      paymentType: PaymentType.ADFALI,
      isActive: true,
      notes: 'خدمة الدفع بالبطاقة الائتمانية',
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 3,
      nameAr: 'سداد',
      nameEn: 'Sadad',
      menuOrder: 3,
      imageFileUrl: 'https://example.com/paypal.jpg',
      imageFile: null,
      imageFileContentType: '',
      details: 'الدفع بواسطة حساب PayPal',
      feePercentage: 3,
      paymentType: PaymentType.SADAD,
      isActive: true,
      notes: 'خدمة الدفع بواسطة PayPal',
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
  ];

  courses: Course[] = [
    {
      id: 1,
      title: 'Tafsir of the Quran',
      description: 'In-depth explanation and interpretation of the Quran',
      price: 100,
      categories: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/tafsir.jpg',
      coverImageFile: null,
      coverImageFileContentType: null,
      studentsPrice: 80,
      keywords: 'Quran, Tafsir, Interpretation',
      comments: [],
      videos: [],
      overallRating: 4.5,
    },
    {
      id: 2,
      title: 'Hadith Studies',
      description: 'Comprehensive study of the Hadith literature',
      price: 150,
      categories: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/hadith-studies.jpg',
      coverImageFile: null,
      coverImageFileContentType: null,
      studentsPrice: 80,
      keywords: 'Hadith, Sunnah, Islamic Studies',
      comments: [],
      videos: [],
      overallRating: 4.5,
    },
    {
      id: 3,
      title: 'Fiqh (Islamic Jurisprudence)',
      description: 'Detailed study of Islamic legal rulings and jurisprudence',
      price: 120,
      categories: [],
      createdBy: 'admin',
      lastModifiedBy: 'admin',
      language: Language.ARABIC,
      coverImageUrl: 'https://example.com/fiqh.jpg',
      coverImageFile: null,
      coverImageFileContentType: null,
      studentsPrice: 80,
      keywords: 'Fiqh, Islamic Law, Jurisprudence',
      comments: [],
      videos: [],
      overallRating: 4.5,
    },
  ];

  orders: Order[] = [
    {
      id: 1,
      orderNo: 'ORD-123',
      total: 100,
      discount: 10,
      paymentType: PaymentType.MOAMALAT,
      orderStatus: OrderStatus.PAYED,
      payedAt: new Date('2024-01-10'),
      notes: 'Order pending payment',
      learner: { id: 1 } as Learner,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
    {
      id: 2,
      orderNo: 'ORD-456',
      total: 150,
      discount: 20,
      paymentType: PaymentType.ADFALI,
      orderStatus: OrderStatus.PENDING,
      payedAt: new Date('2024-02-01'),
      notes: 'Order paid successfully',
      learner: { id: 1 } as Learner,
      createdBy: 'admin',
      lastModifiedBy: 'admin',
    },
  ];

  // eslint-disable-next-line
  public async up(queryRunner: QueryRunner): Promise<any> {
    const bookRepository = getRepository('book');
    await bookRepository.save(this.books);

    const learnerRepository = getRepository('learner');
    await learnerRepository.save(this.learners);

    const bookBorrowRequestRepository = getRepository('book_borrow_request');
    await bookBorrowRequestRepository.save(this.bookBorrowRequests);

    const categoryRepository = getRepository('category');
    await categoryRepository.save(this.categories);

    const paymentMethodRepository = getRepository('payment_method');
    await paymentMethodRepository.save(this.paymentMethods);

    const courseRepository = getRepository('course');
    await courseRepository.save(this.courses);

    const orderRepository = getRepository('order');
    await orderRepository.save(this.orders);
  }

  // eslint-disable-next-line
  public async down(queryRunner: QueryRunner): Promise<any> {}
}
