export enum BookAvailability {
  AVAILABLE_BOTH = 'AVAILABLE_BOTH',

  AVAILABLE_LIBRARY_ONLY = 'AVAILABLE_LIBRARY_ONLY',

  AVAILABLE_ONLINE_ONLY = 'AVAILABLE_ONLINE_ONLY',

  RESERVED = 'RESERVED',

  UNAVAILABLE = 'UNAVAILABLE',
}
